# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20160228_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='data_reviewed',
            new_name='date_reviewed',
        ),
    ]
